[package]
name = "miniprof"
version = "0.1.0"
authors = ["ykS"]
edition = "2018"

[lib]
name = "miniprof"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[dependencies]
once_cell = "1.8.0"

[features]
runprof = []

[workspace]
members = [
    "miniprof_test"
]